import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion"
import { Search, MessageCircle, Mail, Phone, ArrowRight, Users, Building, Lightbulb, Vote } from "lucide-react"

export default function HelpCenterPage() {
  const categories = [
    {
      icon: Users,
      title: "Getting Started",
      description: "Learn the basics of using Mipripity",
      articles: 8,
    },
    {
      icon: Building,
      title: "Property Management",
      description: "How to add and manage your properties",
      articles: 12,
    },
    {
      icon: Vote,
      title: "Voting & Evaluation",
      description: "Understanding our voting system",
      articles: 6,
    },
    {
      icon: Lightbulb,
      title: "AI Prospects",
      description: "Making the most of AI-powered insights",
      articles: 5,
    },
  ]

  const faqs = [
    {
      question: "What is Mipripity and how does it work?",
      answer:
        "Mipripity is a community-driven property evaluation platform that combines user voting with AI-powered insights. Users can submit properties for evaluation, vote on property values, and receive AI-generated investment prospects. Our platform democratizes property assessment by leveraging collective wisdom and advanced technology.",
    },
    {
      question: "How do I add a property for evaluation?",
      answer:
        "To add a property, you need to create an account and log in. Then click the 'Add Property' button, fill in the required details including title, description, location, category, and upload images. Once submitted, your property will be available for community voting and will receive AI-generated prospects.",
    },
    {
      question: "What are AI Prospects and how are they generated?",
      answer:
        "AI Prospects are investment and development suggestions generated by our artificial intelligence system based on property category, location, estimated worth, and market trends. These prospects provide ideas for property improvement, investment opportunities, and potential returns on investment.",
    },
    {
      question: "How does the voting system work?",
      answer:
        "Registered users can vote on properties using predefined options specific to each property category. For example, residential properties might have options like 'Undervalued', 'Fairly Priced', or 'Overvalued'. Voting results are displayed as statistics showing community consensus on property values.",
    },
    {
      question: "Is my personal information secure?",
      answer:
        "Yes, we take data security seriously. All personal information is encrypted and stored securely. We follow industry best practices for data protection and never share your personal information with third parties without your explicit consent. You can review our Privacy Policy for detailed information.",
    },
    {
      question: "Can I edit or delete my property listings?",
      answer:
        "Yes, you can edit your own property listings by going to the property details page and clicking the 'Edit' button. You can update information like title, description, location, and estimated worth. Property deletion is available through your dashboard or by contacting our support team.",
    },
    {
      question: "How accurate are the property evaluations?",
      answer:
        "Our evaluations combine community wisdom with AI analysis to provide comprehensive insights. While we strive for accuracy, evaluations should be used as guidance alongside professional appraisals. The accuracy improves with more community participation and data points.",
    },
    {
      question: "What types of properties can I list?",
      answer:
        "You can list various property types including Residential (houses, apartments), Commercial (offices, retail spaces), Land (plots, agricultural land), and Materials (construction materials, building supplies). Each category has specific voting options and AI prospect templates.",
    },
    {
      question: "How do I contact property owners?",
      answer:
        "Property owner contact information is displayed on property detail pages when provided. This typically includes phone numbers (often WhatsApp) and email addresses. Always respect privacy and use contact information responsibly for legitimate property inquiries.",
    },
    {
      question: "Is Mipripity free to use?",
      answer:
        "Yes, Mipripity is currently free to use. You can create an account, add properties, vote on evaluations, and access AI prospects at no cost. We may introduce premium features in the future, but core functionality will remain free for our community.",
    },
  ]

  const quickLinks = [
    { title: "Create Account", href: "/register", icon: Users },
    { title: "Add Property", href: "/add-property", icon: Building },
    { title: "Browse Properties", href: "/properties", icon: Search },
    { title: "AI Prospects", href: "/prospectProperties", icon: Lightbulb },
  ]

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-100">
      {/* Hero Section */}
      <section className="py-20 px-4">
        <div className="container mx-auto max-w-4xl text-center">
          <Badge className="mb-4 bg-gradient-to-r from-blue-500 to-purple-500 text-white">Help Center</Badge>
          <h1 className="text-5xl md:text-6xl font-bold bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 bg-clip-text text-transparent mb-6">
            How can we help you?
          </h1>
          <p className="text-xl text-slate-600 mb-8 max-w-2xl mx-auto">
            Find answers to your questions, learn how to use Mipripity effectively, and get the support you need.
          </p>

          {/* Search Bar */}
          <div className="relative max-w-2xl mx-auto mb-12">
            <Search className="absolute left-4 top-1/2 transform -translate-y-1/2 text-slate-400 h-5 w-5" />
            <Input
              placeholder="Search for help articles, guides, and FAQs..."
              className="pl-12 h-14 text-lg bg-white/90 backdrop-blur-sm border-slate-200 shadow-lg"
            />
            <Button className="absolute right-2 top-2 h-10">Search</Button>
          </div>
        </div>
      </section>

      {/* Quick Links */}
      <section className="py-12 px-4">
        <div className="container mx-auto max-w-6xl">
          <h2 className="text-3xl font-bold text-center text-slate-800 mb-8">Quick Actions</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {quickLinks.map((link, index) => (
              <Card
                key={index}
                className="border-0 shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-1 bg-white/90 backdrop-blur-sm"
              >
                <CardContent className="p-6 text-center">
                  <link.icon className="h-12 w-12 mx-auto text-blue-600 mb-4" />
                  <h3 className="font-semibold text-slate-800 mb-2">{link.title}</h3>
                  <Button asChild variant="outline" size="sm">
                    <Link href={link.href}>
                      Get Started
                      <ArrowRight className="ml-2 h-4 w-4" />
                    </Link>
                  </Button>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Help Categories */}
      <section className="py-16 px-4 bg-white/80 backdrop-blur-sm">
        <div className="container mx-auto max-w-6xl">
          <h2 className="text-3xl font-bold text-center text-slate-800 mb-12">Browse by Category</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {categories.map((category, index) => (
              <Card
                key={index}
                className="border-0 shadow-lg hover:shadow-xl transition-all duration-300 hover:-translate-y-2 cursor-pointer bg-white"
              >
                <CardHeader className="text-center">
                  <category.icon className="h-12 w-12 mx-auto text-blue-600 mb-4" />
                  <CardTitle className="text-xl">{category.title}</CardTitle>
                  <CardDescription>{category.description}</CardDescription>
                </CardHeader>
                <CardContent className="text-center">
                  <Badge variant="outline" className="text-blue-600 border-blue-200">
                    {category.articles} articles
                  </Badge>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-16 px-4">
        <div className="container mx-auto max-w-4xl">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-slate-800 mb-4">Frequently Asked Questions</h2>
            <p className="text-xl text-slate-600">Find quick answers to the most common questions about Mipripity</p>
          </div>

          <Card className="border-0 shadow-xl bg-white/90 backdrop-blur-sm">
            <CardContent className="p-6">
              <Accordion type="single" collapsible className="space-y-4">
                {faqs.map((faq, index) => (
                  <AccordionItem
                    key={index}
                    value={`item-${index}`}
                    className="border border-slate-200 rounded-lg px-4"
                  >
                    <AccordionTrigger className="text-left font-medium text-slate-800 hover:text-blue-600">
                      {faq.question}
                    </AccordionTrigger>
                    <AccordionContent className="text-slate-600 leading-relaxed pt-2">{faq.answer}</AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* Contact Support */}
      <section className="py-16 px-4 bg-gradient-to-r from-blue-600 to-purple-600">
        <div className="container mx-auto max-w-4xl text-center">
          <h2 className="text-3xl font-bold text-white mb-6">Still Need Help?</h2>
          <p className="text-xl text-blue-100 mb-8 max-w-2xl mx-auto">
            Can't find what you're looking for? Our support team is here to help you with any questions or issues.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <Card className="border-0 shadow-lg bg-white/10 backdrop-blur-sm text-white">
              <CardContent className="p-6 text-center">
                <MessageCircle className="h-12 w-12 mx-auto text-blue-200 mb-4" />
                <h3 className="font-semibold mb-2">Live Chat</h3>
                <p className="text-blue-100 text-sm mb-4">Chat with our support team in real-time</p>
                <Button variant="outline" className="text-blue-600 border-white hover:bg-white bg-transparent">
                  Start Chat
                </Button>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-lg bg-white/10 backdrop-blur-sm text-white">
              <CardContent className="p-6 text-center">
                <Mail className="h-12 w-12 mx-auto text-blue-200 mb-4" />
                <h3 className="font-semibold mb-2">Email Support</h3>
                <p className="text-blue-100 text-sm mb-4">Get detailed help via email</p>
                <Button asChild variant="outline" className="text-blue-600 border-white hover:bg-white bg-transparent">
                  <Link href="/contact">Send Email</Link>
                </Button>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-lg bg-white/10 backdrop-blur-sm text-white">
              <CardContent className="p-6 text-center">
                <Phone className="h-12 w-12 mx-auto text-blue-200 mb-4" />
                <h3 className="font-semibold mb-2">Phone Support</h3>
                <p className="text-blue-100 text-sm mb-4">Speak directly with our team</p>
                <Button variant="outline" className="text-blue-600 border-white hover:bg-white bg-transparent">
                  Call Now
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </div>
  )
}
